import { convertToRgba } from "../utils/colors";

export const Colors = {
  TRANS001: "#BEBEBE12",
  GREEN: "green",
  ERROR: "red",
  BLUE_LIGHT: "#3788E6",
  BLACK: "#000000",
  GRAY: "#222B31",
  CYAN: "#DEFF00",
  SLATE: "#171717",
  BG: "#0a0a0a",
  CYAN_LIGHT: "#E7FF85",
  GRAY_BG: "#222B31",
  GRAY_BG_LIGHT: "#1D2636",
  GRAY_BG_LIGHT_BRIGHT: "#223046",
  GRAY_PROFILE: "#192127",
  GRAY_DARK: "#0F0F0F",
  RED_REMOVE_ACTIONS: "#FF0000",
  GRAY_BG_CE: "#1C2226",
  GREEN_SPOTIFY: "#10e14b",
  BLUE_DARK: "#0B131A",
  BLUE_SEMI_DARK: "#0E1941",
  BLUE_INPUT: "#1B212A",
  BLUE_INPUT_LIGHT: "#162533",
  BLUE: "#001E8A",
  GRAY_MEDIUM: "#92949c",
  GRAY_950: "#171717",
  GRAY_900: "#231f20",
  GRAY_850: "#2d2d2d",
  GRAY_600: "#646464",
  GRAY_500: "#8A8A8A",
  GRAY_400: "#BEBEBE",
  GRAY_LIGHT: "#999999",
  GRAY_SEMI_LIGHT: "#696969",
  WHITE: "#ffffff",
  SEMI_GRAY: "#FEFEFF",
  RED: "red",
  POPUP_BLUE: "#10183E",
  PINK: "#FF4ACC",
  ORANGE: "#FF6528",
  PURPLE: "#9200F7",
  ANIMATIONS: {
    PINK: "#6C004E",
    GREEN: "#004125",
    BLUE: "#001E8A",
    BLACK: "#000",
  },
  GRAY_TIME: "#444444",
};

export const ScreenNames = {
  MANIFESTO: "Manifesto",
  HOME: "Home",
  LOGIN: "Login",
  WELCOME_SCREEN: "WelcomeScreen",
  LOGIN_EMAIL: "LoginEmailScreen",
  SIGNUP: "SIGNUP",
  SIGNUP_EMAIL: "SignupEmailScreen",
  AUTH: "Auth",
  RESET_PW: "ResetPW",
  ONBOARDING_USERNAME: "Onboarding",
  ONBOARDING_VIDEO: "Onboarding2",
  ONBOARDING_INTRO: "OnboardingIntro",
  ONBOARDING_USER_TYPE: "OnboardingUserType",
  ONBOARDING_LOCATION_SELECTOR: "OnboardingLocationSelector",
  TRIP_INTRO: "TripIntro",
  TAB1: "Tab1", // deprecated
  TAB2: "Tab2",
  TAB3: "Tab3", // deprecated
  TAB4: "Tab4", // deprecated
  TAB5: "Tab5",
  TAB_CREATE: "Tab_Create",
  TAB_HOME: "Tab_Home",
  TAB_MESSENGER: "Tab_Messenger",
  TAB_PROFILE: "Tab_Profile",
  TRPPN_MODAL: "TrppnModal",
  EVENT_DETAIL: "EventDetail",
  EDIT_PROFILE: "EditProfile",
  CHAT_PROFILE: "ChatProfile",
  FOLLOWER_PROFILE: "FollowerProfile",
  FOLLOWING_PROFILE: "FollowingProfile",
  EVENT_CREATE: "CreateEvent",
  EVENT_CREATE_INVITES: "InvitesScreen",
  TRIP_CREATE: "CreateTrip",
  LOCATION_SCREEN: "LocationScreen",
  LOCATION_EVENT_SCREEN: "LocationEventScreen",
  USER_PROFILE: "UserProfile",
  COMMENTS_SCREEN: "CommentsScreen",
  USER_LIST_SCREEN: "UserListScreen",
  INVITE_USERS_SCREEN: "InviteUsersScreen",
  POST_FULL_VIEW: "FullPostView",
  LIVE_FEED_SCREEN: "LiveFeedScreen",
  SHARE_MODAL: "ShareView",
  FEED_SCREEN: "FeedScreen",
  CHAT_NEW: "ChatNewScreen",
  CHAT_DETAILS: "ChatDetailsScreen",
  IMAGE_SCREEN: "ImageScreen",
  CAMERA_SCREEN: "CameraScreen",
  TRIP_DETAILS: "TripDetails",
  LOCATION_PREVIEW: "LocationPreviewScreen",
  MEMORIES: "MemoriesScreen",
  POINTS: "PointsScreen",
  CHANNELS_CREATE: "CreateChannelScreen",
  EMAIL_VERIFICATION: "EmailVerificationScreen",
  TERMS: "TermsScreen",
  USERNAME_MODAL: "UsernameModal",
  CHANGE_PASSWORD: "ChangePasswordScreen",
  GROUPS_INTRO: "GroupsIntro",
  EVENTS_INTRO: "EventsIntro",
};

export const FONT_SIZES = {
  XXXLARGE: 50,
  XXLARGE: 38,
  XLARGE: 32,
  LARGE: 28,
  SEMI_LARGE: 18,
  MEDIUM: 16,
  SEMI_SMILE: 14,
  SMALL: 12,
  XSMALL: 10,
  XXSMALL: 8,
};

export const FONT_FAMILIES = {
  REGULAR: "PPRightGroteskText-CompactMedium",
  MEDIUM: "PPRightGrotesk-Regular",
  SEMI_BOLD: "PPRightGrotesk-Medium",
  BLACK: "PPRightGroteskText-WideBold",
};

export const RADIUS = {
  FULL: 500,
  LARGE: 24,
  MEDIUM: 16,
  SMALL: 10,
};

const PADS = {
  LARGE: 16,
  DEFAULT: 12,
  SMALL: 8,
};

const AVATAR_SIZES = {
  LARGE: 132,
  SMALL: 53,
  XSMALL: 40,
  XXSMALL: 34,
};

export const FONT_VARIANTS = {
  body1: {
    fontFamily: FONT_FAMILIES.MEDIUM,
    fontSize: FONT_SIZES.MEDIUM,
  },
  body2: {
    fontFamily: FONT_FAMILIES.MEDIUM,
    fontSize: FONT_SIZES.SEMI_SMILE,
  },
  body3: {
    fontFamily: FONT_FAMILIES.MEDIUM,
    fontSize: FONT_SIZES.SMALL,
  },
  bodyL: {
    fontFamily: FONT_FAMILIES.MEDIUM,
    fontSize: FONT_SIZES.SEMI_LARGE,
  },
  bodyXl: {
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    fontSize: FONT_SIZES.XLARGE,
  },
  bodyXxl: {
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    fontSize: 48,
  },
  nav1: {
    fontFamily: FONT_FAMILIES.MEDIUM,
    fontSize: FONT_SIZES.MEDIUM,
    textTransform: "uppercase",
  },
  nav2: {
    fontFamily: FONT_FAMILIES.MEDIUM,
    fontSize: FONT_SIZES.SMALL,
    textTransform: "uppercase",
  },
  nav3: {
    fontFamily: FONT_FAMILIES.MEDIUM,
    fontSize: FONT_SIZES.XSMALL,
    textTransform: "uppercase",
  },
  MH7: {
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    fontSize: 24,
  },
  MH8: {
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    fontSize: 16,
  },
};

export const BUTTON_VARIANTS = {
  primary: {
    backgroundColor: Colors.CYAN,
    color: Colors.BG,
    letterSpacing: 0,
    paddingVertical: 20,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.SEMI_LARGE + 2,
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    alignSelf: "stretch",
  },
  lightGray: {
    backgroundColor: Colors.GRAY_400,
    color: Colors.GRAY_850,
    letterSpacing: 0,
    paddingVertical: 20,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.SEMI_LARGE + 2,
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    alignSelf: "stretch",
  },
  darkGray: {
    backgroundColor: Colors.GRAY_900,
    color: Colors.GRAY_400,
    letterSpacing: 0,
    paddingVertical: 20,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.SEMI_LARGE + 2,
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    alignSelf: "stretch",
  },
  darkChip: {
    backgroundColor: Colors.SLATE,
    color: Colors.GRAY_400,
    letterSpacing: 0,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    alignSelf: "stretch",
  },
  lightChip: {
    backgroundColor: Colors.GRAY_400,
    color: Colors.GRAY_850,
    letterSpacing: 0,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    alignSelf: "stretch",
  },
  tertiary: {
    backgroundColor: "transparent",
    color: Colors.GRAY_400,
    letterSpacing: 0,
    paddingVertical: 16,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.SEMI_LARGE + 2,
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    alignSelf: "stretch",
  },
  cancel: {
    backgroundColor: Colors.GRAY_900,
    color: Colors.ORANGE,
    letterSpacing: 0,
    paddingVertical: 20,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.SEMI_LARGE + 2,
    fontFamily: FONT_FAMILIES.SEMI_BOLD,
    alignSelf: "stretch",
  },
  white: {
    backgroundColor: Colors.WHITE,
    color: Colors.BLUE,
    paddingVertical: 15,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.SEMI_LARGE + 1,
    fontFamily: FONT_FAMILIES.REGULAR,
    alignSelf: "stretch",
  },
  whiteSmall: {
    backgroundColor: Colors.WHITE,
    color: Colors.BLUE,
    paddingVertical: 13,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.SEMI_LARGE + 1,
    alignSelf: "flex-start",
  },
  blue: {
    backgroundColor: Colors.BLUE,
    color: Colors.WHITE,
    paddingVertical: 15,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.SEMI_LARGE + 1,
    alignSelf: "stretch",
  },
  blueSmall: {
    backgroundColor: Colors.BLUE,
    color: Colors.WHITE,
    paddingVertical: 13,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.SEMI_LARGE + 1,
    alignSelf: "flex-start",
  },
  add: {
    backgroundColor: Colors.CYAN_LIGHT,
    color: Colors.BLACK,
    paddingVertical: 10,
    paddingHorizontal: 16,
    fontSize: FONT_SIZES.SEMI_LARGE + 1,
    alignSelf: "stretch",
  },
  addSmall: {
    backgroundColor: Colors.CYAN_LIGHT,
    color: Colors.BLACK,
    paddingVertical: 7,
    paddingHorizontal: 16,
    fontSize: FONT_SIZES.SEMI_LARGE + 1,
    alignSelf: "flex-start",
  },
  trp: {
    backgroundColor: convertToRgba(Colors.WHITE, 1),
    color: Colors.BLUE,
    paddingVertical: 7,
    paddingHorizontal: 24,
    fontSize: FONT_SIZES.LARGE + 2,
    alignSelf: "flex-start",
  },
  reconnect: {
    backgroundColor: convertToRgba(Colors.ANIMATIONS.PINK, 0.4),
    color: Colors.CYAN,
    paddingVertical: 7,
    paddingHorizontal: 24,
    fontSize: 27,
    borderColor: Colors.CYAN,
  },
};

export const Constants = {
  INITIAL_HEIGHT: 256,
  FONT_SIZES,
  FONT_FAMILIES,
  FONT_VARIANTS,
  BUTTON_VARIANTS,
  RADIUS,
  AVATAR_SIZES,
  PADS,
  COLORS: undefined,
  LOCAL_EVENT_DISTANCE: 0.1,
  NUMBER_OF_HOURS_FOR_EVENT_END: 2,
  MAX_CHARS_TRIP_NAME: 25,
};
